### ISSUE TITLE
Not working on macos < 11.0, and fix

### ISSUE THREAD

**Issue by jawsoftware** [neilsardesai/Mouse-Finder#1]
The project as is does not compile nor works under previous system versions.

I compiled it successfully with the following changes:
- Set Deployement Target to 10.12 (won't compile if < 10.12)
- Change "@main" to "@NSApplicationMain" in line 10 of AppDelegate.swift
- Rebuild; XCode will give another error but it can automatically fix it (Using "fix" button); build it again

Tested and working on macos 10.14

**Comment by neilsardesai** [comment]
Hello,
Thanks for the report, but this is entirely intentional, not an issue. Mouse Finder’s icon is based on the system Finder icon design in Big Sur, since the intention is to replace the system Finder icon. If I were to support versions of macOS earlier than Big Sur, I would also need to design icons to match those of earlier versions of the system Finder app, which I have no intention of doing. But if you would like to run this project on earlier versions of macOS and design icons to match earlier versions of Finder yourself, I would encourage you to fork the repo.
