### ISSUE TITLE
macOS version?

### ISSUE THREAD

**Issue by plpowers** [neilsardesai/Mouse-Finder#2]
It seems this only works with macOS 10.16.  
Is there a prior version that might work for 10.15, etc.?
Perhaps a note about min os??
THX

**Comment by neilsardesai** [comment]
Correct, this project only supports macOS Big Sur and above, since the intention is to replace the system Finder icon with one that looks identical to the one in Big Sur, with the exception that the icon’s eyes follow the mouse pointer. This wouldn’t work in earlier versions of macOS, since the Finder icon has a different design in macOS Catalina and below. If you’d like to run this project on an earlier version of macOS, you’re welcome to fork the repo, lower the deployment target (there are no Big Sur-specific API requirements), and supply your own icon designs that match the Finder icon on your OS version.
